### ISSUE TITLE
testsuite fails since Attean 0.029 which requires file_extensions

### ISSUE THREAD

**Issue by jonassmedegaard** [kjetilk/p5-atteanx-serializer-rdfa#1]
Attean 0.029 requires file_extensions, leading to testsuite failures: https://bugs.debian.org/982722

[this patch](https://salsa.debian.org/perl-team/modules/packages/libatteanx-serializer-rdfa-perl/-/blob/master/debian/patches/1001_add_file_extensions.patch) makes testsuite succeed - in case that's helpful (not sure if this module truly covers those extensions - and if perhaps something is needed to avoid clashing with Attean already declaring SPARQLHTML as having extension `html`).

**Comment by kjetilk** [comment]
Yes, indeed, that patch should cover this case. Do you want to submit it as a PR?
